-- 코드를 입력하세요
SELECT INFO.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO INFO JOIN REST_REVIEW REVIEW
ON INFO.REST_ID = REVIEW.REST_ID
WHERE INFO.ADDRESS LIKE('서울%')
GROUP BY INFO.REST_ID
ORDER BY AVG(REVIEW_SCORE) DESC, INFO.FAVORITES DESC
;
