-- 코드를 작성해주세요
SELECT t3.ITEM_ID, t3.ITEM_NAME, t3.RARITY
FROM ITEM_INFO t1 JOIN
    ITEM_TREE t2 ON t1.ITEM_ID = t2.PARENT_ITEM_ID
    JOIN ITEM_INFO t3 on t3.ITEM_ID = t2.ITEM_ID
WHERE t1.RARITY = 'RARE'
ORDER BY t3.ITEM_ID DESC;